# This won't work - the task is in a container and cli auth is trying to do a url open....won't work.
# Run it manually from a bash prompt instead.

tasks:
  - init: |
      npm install
      gp sync-done installation
    env:
      DEBUG: '*'
      BROWSER: gp preview --external
  - init: gp sync-await installation
    command: npm run start
    env:
      DEBUG: '*'
      BROWSER: gp preview --external
  - init: gp sync-await installation
    command: gp ports await 8080 && gp preview $(gp url 8080)

ports:
  - port: 3000
    name: OauthCallback
    onOpen: ignore
    visibility: public
  - port: 8080
    name: WebViz
    onOpen: open-browser
    visibility: public